### ISSUE TITLE
Dahua new firmware

### ISSUE THREAD

**Issue by adminpkz** [mcw0/Tools#11]
Hi, How did you manage to get the firmware from the NVR?
It appears they have a new format which I  can't extract.
For example [http://ftp.viatec.ua/Dahua/Firmware/NVR/AI/NVR5xxx-I/DH_NVR5XXX-I_MultiLang_V4.001.0000000.3.R.201022.bin](url).

**Comment by mcw0** [comment]
Hi @adminpkz , nothing I will not disclose for now, too much research and work behind that, I don't want to have that loophole closed for now. Sorry.
