### ISSUE TITLE
Dahua-JSON-Debug-Console-v2 issue with dhConsole.json on startup

### ISSUE THREAD

**Issue by riogrande75** [mcw0/Tools#12]
With latest changes in Dahua-JSON-Debug-Console-v2 login/password save was introduced, but the script does not start without manually generated file _dhConsole.json_, even when parameter --save was issued.
`riogrande75@hphost.munich:/home/rio/dahua# python3 Dahua-JSON-Debug-Console-v2.py --rhost 192.168.xx.yy --proto dhip --rport 5000 --auth admin:xxyyzz --save`
`[*] [Dahua JSON Debug Console 2019-2021 bashis <mcw noemail eu>]`
`[-] ReadHosts: [Errno 2] No such file or directory: 'dhConsole.json'`
`[-] Host "False" do not exist`
`[*] All done`

**Comment by mcw0** [comment]
Thanks.

Fixed that and few other.
