### ISSUE TITLE
Simple fix for self.GetRemoteInfo('device') and self.GetRemoteInfo('certificate')

### ISSUE THREAD

**Issue by dharders** [mcw0/Tools#4]
Hi,

Fantastic tool you have developed here!

I was just playing with my Dahua DHI-NVR4108-8P-4KS2 **using DVRIP** and found no data being returned for:

```python
   self.GetRemoteInfo('device')    # or self.GetRemoteInfo('certificate')
```

It would just timeout after 2 seconds with the message ```[-] I haven't received anything from remote!!```

After playing with Wireshark and SmartPSS I noticed the packets being sent from the official SmartPSS application included an additional JSON field of ``` { ..., "params": null, ... }```, so I just updated all of the ```query_args``` objects in your script function ```def GetRemoteInfo(self, msg)``` to include ```"params": None"```.  

i.e. From
```python
query_args = {
	"method":"magicBox.getSoftwareVersion",
	"session":self.SessionID,
	"id":self.ID
   }
```

To
```python
query_args = {
	"method":"magicBox.getSoftwareVersion",
	"session":self.SessionID,
	"id":self.ID,
	"params": None
   }
```

Now calling the function(s) returns data as expected. I added ```"params": None``` to **ALL** of the query_args objects within GetRemoteInfo()

I thought I'd just write my solution here instead of a pull request as I'm not sure if this is a DVRIP specific issue or if it upsets other devices, but came in super handy for me and thought it might help someone else.

Thanks again for releasing this tool!

**Comment by dharders** [comment]
This also applies to ```listService()``` too

**Comment by mcw0** [comment]
Cool, thanks a lot for info, will try that with my different devices.

**Comment by mcw0** [comment]
Awesome, I could not see it breaking something else with my devices. I have included this in next update, still I have some other new and unfinished updates, so if you could make a pull I'll merge it.
