### ISSUE TITLE
Potential locking issue in P2P method

### ISSUE THREAD

**Issue by Antori91** [mcw0/Tools#6]
Thanks again for this amazing code.

I've encountered a lock issue when we lost the Dahua box for a short period. To avoid it, I suggest a minor change in the console code. This modification consists to add before line 397 the following single line code: if self.lock.locked (): self.lock.release ()
The code will become:

		#
		# We must expect there is no output from remote device
		# Some debug cmd do not return any output, some will return after timeout/failure, most will return directly
		#
		TIME = 0.5
		TIMEOUT = TIME

		while True:
			try:
				tmp = len(data)
				data += self.remote.recv(numb=8192,timeout=TIMEOUT).decode('latin-1')
				if not len(data):
					# Give few more seconds if there are not data, P2P_timeout() will take anything later
					if TIMEOUT == TIME:
						TIMEOUT = 2
						continue
				if tmp == len(data):
					break
			except Exception as e:
				if self.lock.locked (): self.lock.release () # line to add                             
				self.socket_event.set()
				log.failure(str(e)) # line to eventually add
				return None
                
To illustrate the issue, I use the two programs enclosed:
- DahuaBox.py to simulate a Dahua Box
- console.py to simulate a client.

I run the DahuaBox and then the console.py. The console logins to the DahuaBox and then send keepalive messages. If I kill the DahuaBox and restart it later, I can see
the console reconnecting smoothly to the DahuaBox and then sending again KeepAlive messages. Then I comment the line if self.lock.locked(): self.lock.release() in console.py (see  below) and 
restart DahuaBox and console.  Then I kill again the DahuaBox and restart it later. This time, the console is reconnecting only partially and its watchdog triggered after 60s due to the locking. 

        data=''       
        TIME = 0.5
        TIMEOUT = TIME
        while True:
            try:
                tmp = len(data)
                data += self.remote.recv(numb=8192,timeout=TIMEOUT).decode('latin-1')
                if not len(data):
                    if TIMEOUT == TIME:
                        TIMEOUT = 2
                        continue
                print( "[" + str(datetime.datetime.now()) + " P2P.3_RX] " + data)
                if tmp == len(data):
                    break
            except Exception as e:
                #self.socket_event.set()
                self.VTH_ON_LINE = self.P2P_traceError() # KO
                print("[" + str(datetime.datetime.now()) + " P2P.3_RX_FAILURE] Receiving failure with error code: {}".format(str(e)) )
                #if self.lock.locked(): self.lock.release()
                return None 

[console.zip](https://github.com/mcw0/Tools/files/4544183/console.zip)
[DahuaBox.zip](https://github.com/mcw0/Tools/files/4544184/DahuaBox.zip)

**Comment by mcw0** [comment]
Nice stuff dude, let me play a bit with this, but already while reading I am sure you found a bug :)

**Comment by mcw0** [comment]
Added your code, thanks :)
